config/routes.rb
Rails.application.routes.draw do
  resources :flat_types
  resources :flats
  resources :buildings
  devise_for :users
  root 'societies#index'
  resources :societies

end

app/controllers/flat_types_controller.rb
class FlatTypesController < ApplicationController
  before_action :set_flat_type, only: [:show, :edit, :update, :destroy]

  # GET /flat_types
  # GET /flat_types.json
  def index
    @flat_types = FlatType.all
  end

  # GET /flat_types/1
  # GET /flat_types/1.json
  def show
  end

  # GET /flat_types/new
  def new
    @flat_type = FlatType.new
  end

  # GET /flat_types/1/edit
  def edit
  end

  # POST /flat_types
  # POST /flat_types.json
  def create
    @flat_type = FlatType.new(flat_type_params)

    respond_to do |format|
      if @flat_type.save
        format.html { redirect_to @flat_type, notice: 'Flat type was successfully created.' }
        format.json { render :show, status: :created, location: @flat_type }
      else
        format.html { render :new }
        format.json { render json: @flat_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flat_types/1
  # PATCH/PUT /flat_types/1.json
  def update
    respond_to do |format|
      if @flat_type.update(flat_type_params)
        format.html { redirect_to @flat_type, notice: 'Flat type was successfully updated.' }
        format.json { render :show, status: :ok, location: @flat_type }
      else
        format.html { render :edit }
        format.json { render json: @flat_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flat_types/1
  # DELETE /flat_types/1.json
  def destroy
    @flat_type.destroy
    respond_to do |format|
      format.html { redirect_to flat_types_url, notice: 'Flat type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flat_type
      @flat_type = FlatType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flat_type_params
      params.require(:flat_type).permit(:name, :area, :status)
    end
end

app/helpers/flat_types_helper.rb
module FlatTypesHelper
end

app/views/flat_types/_form.html.erb
<%= simple_form_for @flat_type, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= error_span(@flat_type[:name]) %>
  <%= f.input :area %>
  <%= error_span(@flat_type[:area]) %>
  <%= f.input :status %>
  <%= error_span(@flat_type[:status]) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                flat_types_path, :class => 'btn btn-default' %>
<% end %>

app/views/flat_types/edit.html.erb
<%- model_class = FlatType -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/flat_types/index.html.erb
<%- model_class = FlatType -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:area) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @flat_types.each do |flat_type| %>
      <tr>
        <td><%= link_to flat_type.id, flat_type_path(flat_type) %></td>
        <td><%= flat_type.name %></td>
        <td><%= flat_type.area %></td>
        <td><%= flat_type.status %></td>
        <td><%=l flat_type.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_flat_type_path(flat_type), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      flat_type_path(flat_type),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_flat_type_path,
            :class => 'btn btn-primary' %>

app/views/flat_types/new.html.erb
<%- model_class = FlatType -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/flat_types/show.html.erb
<%- model_class = FlatType -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @flat_type.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:area) %>:</strong></dt>
  <dd><%= @flat_type.area %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @flat_type.status %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              flat_types_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_flat_type_path(@flat_type), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              flat_type_path(@flat_type),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>