config/routes.rb
Rails.application.routes.draw do
  resources :flat_types
  resources :flats
  resources :buildings
  devise_for :users
  root 'societies#index'
  resources :societies

end

app/models/society.rb
class Society < ActiveRecord::Base
	has_many :buildings
	has_many :users
end

app/controllers/societies_controller.rb
class SocietiesController < ApplicationController
  before_action :set_society, only: [:show, :edit, :update, :destroy]

  # GET /societies
  # GET /societies.json
  def index
    @society_all = Society.all
  end

  # GET /societies/1
  # GET /societies/1.json
  def show
  end

  # GET /societies/new
  def new
    @society = Society.new
  end

  # GET /societies/1/edit
  def edit
  end

  # POST /societies
  # POST /societies.json
  def create
    @society = Society.new(society_params)

    respond_to do |format|
      if @society.save
        format.html { redirect_to @society, notice: 'Society was successfully created.' }
        format.json { render :show, status: :created, location: @society }
      else
        format.html { render :new }
        format.json { render json: @society.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /societies/1
  # PATCH/PUT /societies/1.json
  def update
    respond_to do |format|
      if @society.update(society_params)
        format.html { redirect_to @society, notice: 'Society was successfully updated.' }
        format.json { render :show, status: :ok, location: @society }
      else
        format.html { render :edit }
        format.json { render json: @society.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /societies/1
  # DELETE /societies/1.json
  def destroy
    @society.destroy
    respond_to do |format|
      format.html { redirect_to societies_url, notice: 'Society was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_society
      @society = Society.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def society_params
      params.require(:society).permit(:name, :address, :pincode, :est_date, :start_date, :builder, :area)
    end
end

app/helpers/societies_helper.rb
module SocietiesHelper
end

app/views/societies/_form.html.erb
<%= simple_form_for @society, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= error_span(@society[:name]) %>
  <%= f.input :address %>
  <%= error_span(@society[:address]) %>
  <%= f.input :pincode %>
  <%= error_span(@society[:pincode]) %>
  <%= f.input :est_date %>
  <%= error_span(@society[:est_date]) %>
  <%= f.input :start_date %>
  <%= error_span(@society[:start_date]) %>
  <%= f.input :builder %>
  <%= error_span(@society[:builder]) %>
  <%= f.input :area %>
  <%= error_span(@society[:area]) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                societies_path, :class => 'btn btn-default' %>
<% end %>

app/views/societies/edit.html.erb
<%- model_class = Society -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/societies/index.html.erb
<%- model_class = Society -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr> 
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:pincode) %></th>
      <th><%= model_class.human_attribute_name(:est_date) %></th>
      <th><%= model_class.human_attribute_name(:start_date) %></th>
      <th><%= model_class.human_attribute_name(:builder) %></th>
      <th><%= model_class.human_attribute_name(:area) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @society_all.each do |society| %>
      <tr>
        <td><%= link_to society.id, society_path(society) %></td>
        <td><%= society.name %></td>
        <td><%= society.address %></td>
        <td><%= society.pincode %></td>
        <td><%= society.est_date %></td>
        <td><%= society.start_date %></td>
        <td><%= society.builder %></td>
        <td><%= society.area %></td>
        <td><%=l society.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_society_path(society), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      society_path(society),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_society_path,
            :class => 'btn btn-primary' %>

app/views/societies/new.html.erb
<%- model_class = Society -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/societies/show.html.erb
<%- model_class = Society -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @society.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @society.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:pincode) %>:</strong></dt>
  <dd><%= @society.pincode %></dd>
  <dt><strong><%= model_class.human_attribute_name(:est_date) %>:</strong></dt>
  <dd><%= @society.est_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:start_date) %>:</strong></dt>
  <dd><%= @society.start_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:builder) %>:</strong></dt>
  <dd><%= @society.builder %></dd>
  <dt><strong><%= model_class.human_attribute_name(:area) %>:</strong></dt>
  <dd><%= @society.area %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              societies_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_society_path(@society), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              society_path(@society),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>